[package]
name = "rua"
version = "0.3.0"
edition = "2021"
authors = ["bzhao@hillstonenet.com"]
description = "A tiny box combining many functionalities."
keywords = ["CLI", "JSON Compilation Database"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
atty = "0.2.14"
chrono = "0.4.33"
clap = { version = "4.5.0", features = ["derive"] }
colored = "2.1.0"
csv = "1.3.0"
libc = "0.2.153"
regex = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
terminal_size = "0.3"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"
strip = true
