[package]
name = "rua"
version = "0.9.0"
edition = "2021"
authors = ["bzhao@hillstonenet.com"]
description = "A dev box for StoneOS project."
keywords = ["CLI"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.23.0"
anyhow = "1.0"
chrono = "0.4.0"
clap = { version = "4.5.0", features = ["derive"] }
console = "0.15.8"
crossterm = "0.27.0"
csv = "1.3.0"
indicatif = "0.17.8"
libc = "0.2.0"
regex = "1.10"
reqwest = { version = "0.12.0", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
walkdir = "2.5.0"

[profile.release]
lto = true
opt-level = "s"
panic = "abort"
strip = true
