[package]
name = "rua"
version = "0.10.2"
edition = "2021"
authors = ["bzhao@hillstonenet.com"]
description = "A dev box for StoneOS project."
keywords = ["CLI"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.24.0"
anyhow = "1.0"
bitflags = "2.6.0"
chrono = "0.4.0"
clap = { version = "4.5.0", features = ["derive"] }
crossterm = "0.28.0"
csv = "1.3.0"
libc = "0.2.0"
regex = "1.10.0"
reqwest = { version = "0.12.0", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
walkdir = "2.5.0"

[profile.release]
lto = true
opt-level = 3
panic = "abort"
strip = true
codegen-units = 1
