[package]
name = "rua"
version = "0.19.0"
edition = "2021"
authors = ["bzhao@hillstonenet.com"]
description = "Dev box for StoneOS project."
keywords = ["CLI"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.24.0"
anstyle = "1.0.8"
anyhow = "1.0"
bitflags = "2.6.0"
chrono = "0.4.0"
clap = { version = "4.5.0", features = ["derive"] }
clap_complete = "4.5.40"
crossterm = "0.28.1"
csv = "1.3.0"
home = "0.5.9"
indicatif = "0.17.9"
libc = "0.2.0"
ratatui = "0.29.0"
regex = "1.10.0"
reqwest = { version = "0.12.0", default-features = false, features = ["rustls-tls"] }
rustix = { version = "0.38.0", features = ["system"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.14.0"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8.19"
url = "2.5.2"
walkdir = "2.5.0"

[profile.release]
lto = true
opt-level = 2
panic = "abort"
strip = true
codegen-units = 1
