use std::path::PathBuf;

use clap::Args;

use crate::core::perfan;

#[derive(Args, Clone, Debug)]
pub(crate) struct PerfanArgs {
    #[arg(help = "Profiling text generated by perfan", value_name = "FILE")]
    pub(crate) file: PathBuf,

    #[arg(
        short = 'o',
        long = "format",
        value_name = "FORMAT",
        default_value = "table",
        help = "Output format"
    )]
    pub(crate) format: perfan::DumpFormat,

    #[arg(
            short = 'e',
            long = "elf",
            visible_aliases= ["exe", "executable"],
            value_name = "ELF",
            help = "Binary files used for addresses resolving"
        )]
    pub(crate) elfs: Vec<PathBuf>,
}
